# Base image from manylinux for x86_64
FROM quay.io/pypa/manylinux_2_28_x86_64

# Set the correct Python paths for CMake
ENV PYTHON_PATH=/opt/python/cp310-cp310
ENV PYTHON_EXECUTABLE=${PYTHON_PATH}/bin/python3.10

# Install wheel (required for building wheels)
RUN ${PYTHON_EXECUTABLE} -m pip install wheel auditwheel

# Set the working directory
WORKDIR /hyperon_das_node
