FROM python:3.12

RUN apt-get update \
 && apt-get -y install cmake \
 && apt-get clean \
 && pip install --no-cache-dir nanobind==2.1.0
 
WORKDIR /opt/das-node/
VOLUME /opt/das-node/
COPY . .

# RUN cmake -S . -B build && cmake --build build
