load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "com_github_grpc_grpc",
    strip_prefix = "grpc-tags-v1.63.0",
    urls = ["https://github.com/grpc/grpc/archive/tags/v1.63.0.tar.gz"],
)

http_archive(
    name = "com_github_singnet_das_proto",
    strip_prefix = "das-proto-0.1.12",
    urls = ["https://github.com/singnet/das-proto/archive/refs/tags/0.1.12.tar.gz"],
)

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()
load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")
grpc_extra_deps()

http_archive(
    name = "com_github_google_googletest",
    strip_prefix = "googletest-1.14.0",
    urls = ["https://github.com/google/googletest/archive/refs/tags/v1.14.0.tar.gz"]
)

new_local_repository(
    name = "mbedcrypto",
    path = "/opt/3rd-party/mbedcrypto",
    build_file_content = '\
cc_library(\
    name = "lib",\
    srcs = ["libmbedcrypto.a"],\
    visibility = ["//visibility:public"],\
)\
'
)
