package(default_visibility = ["//visibility:public"])

cc_library(
    name = "cache_node_lib",
    srcs = glob(["*.cc"]),
    hdrs = glob(["*.h"]),
    includes = ["."],
    deps = [
        "//atom_space_node:atom_space_node_lib"
    ],
)
