name: Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

jobs:
  code-quality:
    uses: ./.github/workflows/run-tests.yml
    secrets: inherit

  tag:
    needs: code-quality
    uses: singnet/das/.github/workflows/run-semver.yml@master
    with:
      version: ${{ github.event.inputs.version }}
      version-strategy: bump-version-from-variable-value
      job-image-namespace: trueagi
      job-image-version-semver: semantic-versioning
      main-branch: master
      version-tag-regex-pattern: /^\d+\.\d+\.\d+$/
      version-require-confirmation: "true"
      title: New version of hyperon-das-node
      deliverable: Library in PyPI named hyperon-das-node
    secrets: inherit

  publish:
    runs-on: ubuntu-22.04
    needs: tag
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update version
        run: sed -i "s/version=.*/version='${{ github.event.inputs.version }}',/" pyproject.toml

      - name: Build (Docker Image)
        run: ./scripts/docker_image_build.sh

      - name: Build (Bazel)
        run: ./scripts/build.sh

      - name: Build (Docker Image Wheel)
        run: ./scripts/docker_image_wheel.sh

      - name: Build (Wheel)
        run: ./scripts/wheel.sh

      - name: Install twine
        run: pip install twine

      - name: Publish Package
        working-directory: wheelhouse
        run: twine upload $(find . -name *.whl | head -n 1) --username __token__ --password ${{ secrets.PYPI_API_TOKEN }} --non-interactive
