name: Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

jobs:
  tag:
    if: github.ref == 'refs/heads/master'
    uses: singnet/das/.github/workflows/run-semver.yml@master
    with:
      version: ${{ github.event.inputs.version }}
      version-strategy: bump-version-from-variable-value
      job-image-namespace: trueagi
      job-image-version-semver: semantic-versioning
      main-branch: master
      version-tag-regex-pattern: /^\d+\.\d+\.\d+$/
      version-require-confirmation: "true"
      title: New version of hyperon-das-node
      deliverable: Library in PyPI named hyperon-das-node
    secrets: inherit

  build:
    runs-on: ubuntu-22.04
    needs: tag
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build (Docker Image)
        run: ./script/docker_image_build.sh

      - name: Build (Bazel)
        run: ./script/build.sh

      - name: Build and publish pypi
        run: ./script/container_tty.sh cat<<EOF
          pip install .
          pip install twine
          twine upload dist/* --username __token__ --password ${{ secrets.PYPI_API_TOKEN }} --non-interactive
          EOF
