name: Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

jobs:
  tag:
    if: github.ref == 'refs/heads/master'
    uses: singnet/das/.github/workflows/run-semver.yml@master
    with:
      version: ${{ github.event.inputs.version }}
      version-strategy: bump-version-from-variable-value
      job-image-namespace: trueagi
      job-image-version-semver: semantic-versioning
      main-branch: master
      version-tag-regex-pattern: /^\d+\.\d+\.\d+$/
      version-require-confirmation: "true"
      title: New version of hyperon-das-node
      deliverable: Library in PyPI named hyperon-das-node
    secrets: inherit

  build:
    runs-on: ubuntu-22.04
    needs: tag
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Login to DockerHub
      #   if: success()
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: docker/Dockerfile
          context: .
          push: false
          tags: trueagi/das:${{ inputs.version }}-das-node,trueagi/das:latest-das-node
