---
name: Run Unit & Integration tests

on:
  workflow_call:

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  build-wheel:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ~3.10
          cache: "pip"

      - name: Build Wheel
        run: make wheel

      - name: Upload das-node-wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: das-node-wheel
          path: wheelhouse/*

  unit-tests-python:
    runs-on: ubuntu-22.04
    needs: build-wheel
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ~3.10
          cache: "pip"

      - name: Download das-node-wheel artifact
        uses: actions/download-artifact@v4
        with:
          name: das-node-wheel
          path: wheelhouse

      - name: Installing das-node-wheel
        run: pip install $(find . -name *.whl -type f | head -n 1)

      - name: Execute Python Unit Test
        run: make test-python

  unit-tests-cpp:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Bazel
        run: make bazel-build

      - name: Execute C++ Unit Test
        run: docker run --rm -i bash -c "make test-cpp"
