---
name: Run Unit & Integration tests

on:
  workflow_call:

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  unit-tests-python:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ~3.10
          cache: "pip"

      - name: Execute Python Unit Test
        run: make test-python

  unit-tests-cpp:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Bazel
        run: make bazel-build

      - name: Execute C++ Unit Test
        run: docker run --rm -i bash -c "make test-cpp"
