---
name: Run DAS Node tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

  workflow_dispatch:

jobs:
  build-bazel:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Build docker image
        run: make cpp-image

      - name: Login to Github Registry
        if: success()
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to repository
        run: |-
          docker tag das-node-builder:latest ghcr.io/das-node-builder:${{ github.sha }}
          docker push ghcr.io/das-node-builder:${{ github.sha }}

  cpp-tests:
    runs-on: ubuntu-22.04
    needs: build-bazel
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Login to Github Registry
        if: success()
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull docker image from registry
        run: |-
          docker pull ghcr.io/das-node-builder:${{ github.sha }}
          docker tag ghcr.io/das-node-builder:${{ github.sha }} das-node-builder:latest

      - name: Run cpp tests
        run: make cpp-test

  wheel-test:
    runs-on: ubuntu-22.04
    needs: build-bazel
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Login to Github Registry
        if: success()
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull docker image from registry
        run: |-
          docker pull ghcr.io/das-node-builder:${{ github.sha }}
          docker tag ghcr.io/das-node-builder:${{ github.sha }} das-node-builder:latest

      - name: Run python tests
        run: make wheeler-test
